version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    command: python3 producer.py
    volumes:
      - ../../kafka-python:/app
    network_mode: host